### ISSUE TITLE
something strange with this lab

### ISSUE THREAD

**Issue by smithWEBtek** [learn-co-curriculum/react-rendering-lab#11]
I had to install 2 things to get the tests to work: 

///////////////////////////////////////////////////////////////////////////////////////
1st Error: 
solved it by running:    npm install --save-dev babel-plugin-transform-react-inline-elements
 
 mocha-multi@0.11.1
added 3 packages in 10.939s
/Users/BradSmith/dev/code4/react-rendering-lab-v-000/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180
          throw new ReferenceError(messages.get("pluginUnknown", plugin, loc, i, dirname));
          ^

ReferenceError: Unknown plugin "transform-react-inline-elements" specified in "/Users/BradSmith/dev/code4/react-rendering-lab-v-000/.babelrc" at 3, attempted to resolve relative to "/Users/BradSmith/dev/code4/react-rendering-lab-v-000"
    at /Users/BradSmith/dev/code4/react-rendering-lab-v-000/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17
    at Array.map (native)

/////////////////////////////////////////////////////////////////////////////////////////
2nd Error: 
solved it by finding missing items in Package.json, snooping through other student repos.

  1) Rating sets the increasing state correctly:
     Error: 
      Enzyme Internal Error: Enzyme expects an adapter to be configured, but found none. To
      configure an adapter, you should call `Enzyme.configure({ adapter: new Adapter() })`
      before using any of Enzyme's top level APIs, where `Adapter` is the adapter
      corresponding to the library currently being tested. For example:

      import Adapter from 'enzyme-adapter-react-15';

      To find out more about this, see http://airbnb.io/enzyme/docs/installation/index.html

/////////////////////////////////////////////////////////////////////////////////////////
3rd Error
I've got all 4 tests passing, as well as the functionality described in the lab. 
The functionality for the last 2 sections does not have any tests. 

///////////////////////////////////////////////////////////////////////////////////////////
4th issue: 
Tests are passing, but Learn online is not acknowledging 'local tests passed'. 
It shows green that I forked the lab, and shows  green that I submitted, but is not showing the tests having passed or failed ( in the browser sidebar).

**Comment by dkStephanos** [comment]
Please address these issues!!
