### ISSUE TITLE
Incredibly strange formatting

### ISSUE THREAD

**Issue by georgelgore** [learn-co-curriculum/react-rendering-lab#15]
see below. should be a paragraph

For this section, we've got a little random .gif generator. Pressing the 'New random .gif!' button will make/perform a request
to giphy and display a new random .gif for us! Neat! Try pressing the button now. You might have noticed
that it takes a bit of time for the new .gif to display. Perhaps we'd like a little indication of the loading. Maybe a
loading bar? Now, in reality you could do this loading bar in React, however for the sake of this example, lets imagine
that the loading bar is done by a different library that React has no control over. You can set this loading bar in the
showLoadingBar() function which is already created for you in <Animation />. Call this function through the
componentWillUpdate() lifecycle method and see that happens! If you've done it correctly you should see a pink loading
bar at the top of the screen every time a new .gif is being loaded.

By the end of this section, the test under <Animation /> should be passing.

**Comment by DanielSeehausen** [comment]
Thank you for spotting this issue George. As discussed in person, this is a style choice we implement with hard breaks before 80 chars. The formatting recreates itself when learn resizes its README markdown display to <80 columns. Will be elevating amongst team to discuss.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.
