### ISSUE TITLE
Babel not cloning properly

### ISSUE THREAD

**Issue by dkStephanos** [learn-co-curriculum/react-rendering-lab#17]
Was getting these issues trying to run 'learn' 

Error: Couldn't find preset "es2015" relative to directory
Error: Couldn't find preset "stage-0" relative to directory

Using 'npm install' with these commands 

babel-preset-es2015
babel-preset-stage-0

**Comment by dkStephanos** [comment]
tests still didn't run correctly, this resolves the babel issues, but the package.json and root.js files were also outdated and had to be copied from here: https://github.com/CurlsandCode/react-rendering-lab-v-000

**Comment by DanielSeehausen** [comment]
pr #19 resolved courtesy @DakotaLMartinez
