### ISSUE TITLE
Possible issue with v8-debug package

### ISSUE THREAD

**Issue by aml7733** [learn-co-curriculum/react-rendering-lab#4]
...
│ └── loose-envify@1.3.1 
├── react-addons-test-utils@15.4.2 
└── react-dom@15.4.2 

npm ERR! Linux 4.8.0-41-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v7.6.0
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE

npm ERR! v8-debug@0.7.7 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the v8-debug@0.7.7 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the v8-debug package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build

**Comment by Lukeghenco** [comment]
This should be resolved with move to Webpack.
