### ISSUE TITLE
Final test missing

### ISSUE THREAD

**Issue by kjleitz** [learn-co-curriculum/react-rendering-lab#5]
The test for `<Pikachu />` (where you are supposed to use `componentDidUpdate()`) is missing.

**Comment by itzsaga** [comment]
I don't see any tests for `componentWillUpdate()` in addition to the missing `componentDidUpdate()` tests.

**Comment by Lukeghenco** [comment]
Thanks for raising the issue. I am not too concerned about this at the moment, but I will add this to my list of tests to add.

**Comment by Lukeghenco** [comment]
Going to move this to a new issue.
